name: 🤔 Question
description: Usage question that isn't answered in docs or discussion
title: "[Question] <title>"
labels: ["type: question"]
body:
- type: textarea
  attributes:
    label: Question
    placeholder: >
      your question here;
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Please pay attention on issues you submitted, because we maybe need more details.
      If no response anymore and we cannot reproduce it on current information, we will **close it**.

